[package]
name = "yew_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-sys = "0.3"
yew = { version = "0.20", features = ["csr"] }

[profile.release]
lto = true
opt-level = "s"
