# use this file for dev

services:
  axum_demo:
    image: rust
    volumes:
      - .:/project
      - /project/target
    ports:
      - 3000:8080
    working_dir: /project
    command: trunk serve
