[build]
# The public URL from which assets are to be served.
public_url = "/"

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = true
# Disable auto-reload of the web app.
no_autoreload = false

# 在 pre_build 阶段执行 "sh .shell/pre_build.sh" 命令
[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [".shell/pre_build.sh"]

# # 在 post_build 阶段执行 "sh .shell/post_build.sh" 命令
# [[hooks]]
# stage = "post_build"
# command = "sh"
# command_arguments = [".shell/post_build.sh"]
