# Workspace cargo config.
# See more on The Cargo Book:
# https://doc.rust-lang.org/cargo/reference/config.html

# sparse protocol is supported by default since rust v1.70.
# [registries.crates-io]
# protocol = "sparse"
